services:
  sena-juicios:
    build: .
    image: sena-juicios:latest
    container_name: sena-juicios
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 5000
      SOFIA_CARPETA: /data/descargas
    volumes:
      - senajuicios:/data/descargas
    shm_size: "1gb"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.juicios.rule=Host(`juicios.areasoftccyt.com`)"
      - "traefik.http.routers.juicios.entrypoints=web"
      - "traefik.http.services.juicios.loadbalancer.server.port=5000"
      - "traefik.docker.network=public"
    networks:
      - public

volumes:
  senajuicios:

networks:
  public:
    external: true
    name: public
